---
#- include_tasks: handlers/main.yml

# Install necessary mysql packages and notify the handlere "Start mysql"
- name: Install MariaDB packages
  apt:
    name:
      - mariadb-common
      - mariadb-server
      - mariadb-client
    update_cache: true
    state: present
  notify:
    - start mysql
    - secure mysql